### ISSUE TITLE
Curate prompts and responses for AI Assistant

### ISSUE THREAD

**Issue by wasimxyz** [lookout-team/lookout#5]
We want to implement an AI assistant that can "take the wheel" for all CRUD operations and return interactive UI components. Something similar to this: https://www.youtube.com/watch?v=br2d_ha7alw&t=65s

### Task breakdown

- For each category of Projects, Sprints, and Tasks, create a list of prompts that a user might enter.
- For every prompt, decide on the appropriate data that ChatGPT should return.
    - This data would then be parsed to invoke the correct controller action.
- If you get a Google doc started, @winstuhn and I could help add some ideas to the list.
- Discuss iterations on Discord and fit to scope.

#### (Rough) Example

Prompt: _"Are the items in this sprint going to be finished in time?"_

Data that might be sent to ChatGPT: Number of items open, capacity, progress, time left in sprint
Data that might be returned: Text response detailing why or why not the sprint might be completed in time

Action invoked: Return text response, **retrieve** open tasks for given sprint in database

### Notes

- Please create your files in `/lib/ai` :)
- Maybe some article / video research on prompting would be a good start.
    - https://www.oneusefulthing.org/p/a-guide-to-prompting-ai-for-what
- This list of prompt-response logic might be good to store in a JSON file.

**Comment by joelhenningsen** [comment]
Initial list of curated prompts and responses completed.
Google Doc Link: https://docs.google.com/document/d/1W8IcWRF6u42LPNUgcr94h3ii6vqnDaVHnjJqnytIlQo/edit#heading=h.amy8vyp8p4d3
