### ISSUE TITLE
Set up ChatGPT Assistants API

### ISSUE THREAD

**Issue by wasimxyz** [lookout-team/lookout#6]
### Task breakdown
- Read documentation for ChatGPT Assistants API
   - https://platform.openai.com/docs/assistants/overview?lang=node.js
- Create account and set up an API key
   - https://platform.openai.com/docs/quickstart?context=node

### Notes
- Set up your files in `/lib/ai` :)
- Do not commit the API key! Create an .env file, make sure it's added to the .gitignore, and store the key there
- Determine what the total cost would be just for development / testing. If needed, we can split the cost.

**Comment by joelhenningsen** [comment]
### Completed:
- Read over ChatGPT Assistants API documentation
- OpenAI account created and single API key created.


![Image](https://github.com/lookout-team/lookout/assets/117242786/1b93472b-38d2-4573-9164-c56b8ae73c83)


- Loaded the account with the minimum amount of $5 credit to use for tokens.

![Image](https://github.com/lookout-team/lookout/assets/117242786/994eec1f-1fb4-4caa-b93f-162631f69763)



### Important Notes:
- Looks like we should use the official [Node.js library created by OpenAI](https://github.com/openai/openai-node)

### Next steps:
- Use the [Assistants Playground](https://platform.openai.com/playground?mode=assistant) to understand how assistants can work for our use case.
- Set up .env file and begin to work on using the ChatGPT Assistant locally.
